# Generated by Django 3.1.8 on 2021-11-26 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_vaccines'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinesRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('doseNumber', models.IntegerField()),
                ('dose_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('provider_name', models.CharField(max_length=100)),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.vaccines')),
            ],
        ),
    ]
