# Generated by Django 3.1.8 on 2021-11-26 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_vaccinesregistered'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProvider',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('providerName', models.CharField(max_length=100)),
                ('totalDose', models.IntegerField()),
                ('driveDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.vaccines')),
            ],
        ),
    ]
