# Generated by Django 3.1.8 on 2021-11-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_bookingdetails_healthprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='status',
        ),
    ]
