# Generated by Django 3.1.8 on 2021-11-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_bookingdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
